import { createHash } from 'node:crypto'
import { readdir, readFile, realpath, stat } from 'node:fs/promises'
import { basename, join, relative, resolve } from 'node:path'

import ignore from 'ignore'

import { detectLanguage, isBinaryPath } from './languages.js'

const MAX_FILE_SIZE_BYTES = 1024 * 1024
const DEFAULT_IGNORES = [
  '.cache',
  '.codesift',
  '.git',
  '.next',
  '.turbo',
  'build',
  'coverage',
  'dist',
  'node_modules',
  'third_party',
  'vendor',
  '__generated__'
]

const SKIPPED_BASENAMES = new Set([
  'bun.lock',
  'bun.lockb',
  'Cargo.lock',
  'composer.lock',
  'Gemfile.lock',
  'package-lock.json',
  'pnpm-lock.yaml',
  'poetry.lock',
  'Pipfile.lock',
  'uv.lock',
  'yarn.lock'
])

const GENERATED_PATH_PATTERNS = [
  /(?:^|\/)__generated__(?:\/|$)/i,
  /(?:^|\/)generated(?:\/|$)/i,
  /(?:^|\/)gen(?:\/|$)/i,
  /(?:^|\/).*\.generated\.[^.\/]+$/i,
  /(?:^|\/).*\.gen\.[^.\/]+$/i,
  /(?:^|\/).*\.min\.[^.\/]+$/i,
  /(?:^|\/).*\.pb\.go$/i,
  /(?:^|\/).*_pb2\.py$/i,
  /(?:^|\/).*_pb\.rb$/i,
  /(?:^|\/).*\.designer\.[^.\/]+$/i
]

const GENERATED_MARKERS = [
  /@generated/i,
  /auto-?generated/i,
  /automatically generated/i,
  /code generated by/i,
  /do not edit/i,
  /generated file/i,
  /this file was generated/i
]

interface IgnoreMatcher {
  basePath: string
  matcher: ReturnType<typeof ignore>
}

export interface ScannedFile {
  absolutePath: string
  relativePath: string
  language: string
  content: string
  hash: string
  size: number
  mtime: number
  generated: boolean
}

export interface ScanResult {
  files: ScannedFile[]
  skippedFiles: number
  skippedSymlinks: number
}

export async function scanRepository(root: string): Promise<ScanResult> {
  const files: ScannedFile[] = []
  let skippedFiles = 0
  let skippedSymlinks = 0
  const repoRoot = resolve(root)
  const repoRealRoot = await realpath(root).catch(() => repoRoot)
  const rootMatchers = [await createDirectoryMatcher(root, '', DEFAULT_IGNORES)]

  async function processFile(absolutePath: string, relativePath: string): Promise<void> {
    if (isBinaryPath(relativePath) || shouldSkipPath(relativePath)) {
      skippedFiles += 1
      return
    }

    const fileStat = await stat(absolutePath)
    if (!fileStat.isFile()) {
      skippedFiles += 1
      return
    }

    if (fileStat.size > MAX_FILE_SIZE_BYTES) {
      skippedFiles += 1
      return
    }

    const buffer = await readFile(absolutePath)
    if (buffer.includes(0)) {
      skippedFiles += 1
      return
    }

    const language = detectLanguage(relativePath)
    if (!language) {
      skippedFiles += 1
      return
    }

    const content = buffer.toString('utf8')
    files.push({
      absolutePath,
      relativePath,
      language,
      content,
      hash: createHash('sha256').update(buffer).digest('hex'),
      size: fileStat.size,
      mtime: fileStat.mtimeMs,
      generated: isGeneratedSource(relativePath, content)
    })
  }

  async function walk(currentDirectory: string, activeRealPaths: Set<string>, inheritedMatchers: IgnoreMatcher[]): Promise<void> {
    const directoryRelativePath = normalizeRelativePath(relative(root, currentDirectory))
    const matchers = directoryRelativePath
      ? [...inheritedMatchers, await createDirectoryMatcher(currentDirectory, directoryRelativePath)]
      : inheritedMatchers
    const entries = await readdir(currentDirectory, { withFileTypes: true })

    for (const entry of entries) {
      const absolutePath = join(currentDirectory, entry.name)
      const relativePath = normalizeRelativePath(relative(root, absolutePath))

      if (entry.isSymbolicLink()) {
        const targetPath = await realpath(absolutePath).catch(() => null)
        if (!targetPath || !isPathInsideRoot(repoRealRoot, targetPath)) {
          skippedSymlinks += 1
          continue
        }

        const targetStat = await stat(absolutePath).catch(() => null)
        if (!targetStat) {
          skippedSymlinks += 1
          continue
        }

        if (targetStat.isDirectory()) {
          if (isIgnored(relativePath, true, matchers)) {
            continue
          }

          if (activeRealPaths.has(targetPath)) {
            skippedSymlinks += 1
            continue
          }

          const nextActiveRealPaths = new Set(activeRealPaths)
          nextActiveRealPaths.add(targetPath)
          await walk(absolutePath, nextActiveRealPaths, matchers)
          continue
        }

        if (targetStat.isFile()) {
          if (isIgnored(relativePath, false, matchers)) {
            continue
          }

          await processFile(absolutePath, relativePath)
          continue
        }

        skippedSymlinks += 1
        continue
      }

      if (isIgnored(relativePath, entry.isDirectory(), matchers)) {
        continue
      }

      if (entry.isDirectory()) {
        const nextRealPath = await realpath(absolutePath).catch(() => absolutePath)
        const nextActiveRealPaths = new Set(activeRealPaths)
        nextActiveRealPaths.add(nextRealPath)
        await walk(absolutePath, nextActiveRealPaths, matchers)
        continue
      }

      if (!entry.isFile()) {
        skippedFiles += 1
        continue
      }

      await processFile(absolutePath, relativePath)
    }
  }

  await walk(root, new Set([repoRealRoot]), rootMatchers)

  files.sort((left, right) => left.relativePath.localeCompare(right.relativePath))
  return { files, skippedFiles, skippedSymlinks }
}

async function createDirectoryMatcher(directory: string, basePath: string, defaults: string[] = []): Promise<IgnoreMatcher> {
  const matcher = ignore().add(defaults)

  for (const fileName of ['.gitignore', '.codesiftignore']) {
    try {
      matcher.add(await readFile(join(directory, fileName), 'utf8'))
    } catch {
      // ignore missing optional ignore files
    }
  }

  return { basePath, matcher }
}

function isIgnored(relativePath: string, isDirectory: boolean, matchers: IgnoreMatcher[]): boolean {
  const candidate = isDirectory ? `${relativePath}/` : relativePath
  let ignored = false

  for (const { basePath, matcher } of matchers) {
    const scopedPath = toScopedIgnorePath(candidate, basePath)
    if (!scopedPath) {
      continue
    }

    const result = matcher.test(scopedPath)
    if (result.ignored) {
      ignored = true
    }

    if (result.unignored) {
      ignored = false
    }
  }

  return ignored
}

function toScopedIgnorePath(candidate: string, basePath: string): string | null {
  if (!basePath) {
    return candidate
  }

  if (candidate === basePath || candidate === `${basePath}/`) {
    return ''
  }

  const prefix = `${basePath}/`
  return candidate.startsWith(prefix) ? candidate.slice(prefix.length) : null
}

function shouldSkipPath(filePath: string): boolean {
  const fileName = basename(filePath)

  if (SKIPPED_BASENAMES.has(fileName)) {
    return true
  }

  return filePath.endsWith('.map')
}

function isGeneratedSource(filePath: string, content: string): boolean {
  return isGeneratedPath(filePath) || hasGeneratedMarker(content) || looksMinified(content)
}

function isGeneratedPath(filePath: string): boolean {
  return GENERATED_PATH_PATTERNS.some((pattern) => pattern.test(filePath))
}

function hasGeneratedMarker(content: string): boolean {
  const header = content.slice(0, 16 * 1024)
  return GENERATED_MARKERS.some((pattern) => pattern.test(header))
}

function looksMinified(content: string): boolean {
  const lines = content.split(/\r?\n/).filter((line) => line.trim().length > 0)
  if (lines.length === 0) {
    return false
  }

  const averageLineLength = lines.reduce((sum, line) => sum + line.length, 0) / lines.length
  const longestLine = lines.reduce((longest, line) => Math.max(longest, line.length), 0)
  return averageLineLength > 300 || longestLine > 2_000
}

function isPathInsideRoot(root: string, target: string): boolean {
  const normalizedRoot = normalizePath(root)
  const normalizedTarget = normalizePath(target)
  return normalizedTarget === normalizedRoot || normalizedTarget.startsWith(`${normalizedRoot}/`)
}

function normalizePath(value: string): string {
  return resolve(value).replace(/\\/g, '/').replace(/\/$/, '')
}

function normalizeRelativePath(value: string): string {
  return value.split('\\').join('/')
}
